version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
    groups:
      security-npm:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      security-actions:
        applies-to: security-updates
        patterns:
          - "*"
      actions:
        patterns: ["*"]
    commit-message:
      prefix: chore
